[package]
name = "vlc-playlist-parser-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.1"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
lazy_static = "1.4.0"
reqwest = { version = "0.11.13", features = ["json", "blocking"] }

[[bin]]
name = "vlc-playlist-parser-proxy"
path = "src/main.rs"
