[package]
name = "vlc-playlist-parser-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
env_logger = "0.10.0"
http = "0.2.8"
lazy_static = "1.4.0"
log = "0.4.17"
reqwest = { version = "0.11.13", features = ["json", "blocking"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
urlencoding = "2.1.2"

[[bin]]
name = "vlc-playlist-parser-proxy"
path = "src/main.rs"
