query(
  $vodID: ID!
  $platform: String!
  $playerBackend: String
  $playerType: String!
) {
  videoPlaybackAccessToken(
    id: $vodID
    params: {
      disableHTTPS: false
      hasAdblock: false
      platform: $platform
      playerBackend: $playerBackend
      playerType: $playerType
    }
  ) {
    signature
    value
  }
}
