query(
  $slug: ID!
  $platform: String!
  $playerBackend: String
  $playerType: String!
) {
  clip(
    slug: $slug
  ) {
    title
    createdAt
    durationSeconds
    language
    game {
      displayName
    }
    broadcaster {
      displayName
    }
    playbackAccessToken(
      params: {
        disableHTTPS: false
        hasAdblock: false
        platform: $platform
        playerBackend: $playerBackend
        playerType: $playerType
      }
    ) {
      signature
      value
    }
  }
}
